questions =  [q
    {"id": 0, "question": "Geschätfsfreiheit ist der beste praktische Weg damit eine Gesellschaft gedeihen kann.", "effects": {"right": 1}},
    {"id": 1, "question": "Spenden anstatt von Sozialhilfe, ist eine bessere Hilfe für Menschen die es benötigen.", "effects": {"right": 1}},
    {"id": 2, "question": "Gehälter sind immer gerecht, da der Arbeitgeber am Besten weiß, was die Arbeit des Angestellten wert ist.", "effects": {"right": 1}},
    {"id": 3, "question": "Es ist die menschliche Natur gierig zu sein.", "effects": {"right": 1}},
    {"id": 4, "question": "\"Ausbeutung\" ist ein veralteter Term, da die Probleme des Kapitalismus der 1800er Jahre nicht mehr existieren.", "effects": {"right": 1}},
    {"id": 5, "question": "Kommunismus ist ein Ideal, das niemals in der Praxis funktionieren kann.", "effects": {"right": 1}},
    {"id": 6, "question": "Besteuerung der Reichen ist eine schlechte Idee, die Gesellschaft wäre ohne dies besser dran.", "effects": {"right": 1}},
    {"id": 7, "question": "Je härter du arbeitest desto höher steigst du auf in der sozialen Ebene.", "effects": {"right": 1}},
    {"id": 8, "question": "Organisationen und Unternehmen kann nicht vertraut werden und sie müssen von der Regierung reguliert/kontrolliert werden.", "effects": {"right": -1}},
    {"id": 9, "question": "Eine Regierung die für alle da ist und sich für jeden sorgt ist eine grundsätzlich gute Idee.", "effects": {"right": -1}},
    {"id": 10, "question": "Das aktuelle Sozialhilfensystem sollte ausgebaut und erweitert werden um weitere Ungleichheiten zu vermindern.(Als Grundsatz wird hier das Welfare System der USA genommen)", "effects": {"right": -1}},
    {"id": 11, "question": "Land/Grund sollte keine Ware zum Kaufen und Verkaufen sein.", "effects": {"right": -1}}
    {"id": 12, "question": "Alle Banken und Industrien sollten verstaatlicht werden.", "effects": {"right": -1}},
    {"id": 13, "question": "(Soziale) Klasse ist aktuell die primäre Einteilung innerhalb einer Gesellschaft.", "effects": {"right": -1}},
    {"id": 14, "question": "Wirtschaftliche Ungleichheit ist zu groß auf der Welt.", "effects": {"right": -1}},
    {"id": 15, "question": "Manchmal ist es richtig, dass die Regierung ihre Bürger eventuell ausspioniert um Terroristen und Extremisten zu bekämpfen.", "effects": {"auth": 1}},
    {"id": 16, "question": "Autoritätspersonen, sofern moralisch richtig, sind etwas gutes für die Gesellschaft.", "effects": {"auth": 1}},
    {"id": 17, "question": "Stärke/Macht sind notwendig für jede beliebige Regierung um zu funktionieren.", "effects": {"auth": 1}},
    {"id": 18, "question": "Lediglich die Regierung ist in der Lage Organisationen/Unternehmen fair und effektiv zu regulieren.", "effects": {"auth": 1}},
    {"id": 19, "question": "Gesellschaft benötigt Strukturen und Bürokratie um zu funktionieren.", "effects": {"auth": 1}},
    {"id": 20, "question": "Mandatory IDs should be used to ensure public safety.", "effects": {"auth": 1}},
    {"id": 21, "question": "In times of crisis, safety becomes more important than civil liberties.", "effects": {"auth": 1}},
    {"id": 22, "question": "If you have nothing to hide, you have nothing to fear.", "effects": {"auth": 1}},
    {"id": 23, "question": "The government should be less involved in the day to day life of its citizens.", "effects": {"auth": -1}},
    {"id": 24, "question": "Without democracy, a society is nothing.", "effects": {"auth": -1}},
    {"id": 25, "question": "Jury nullification should be legal.", "effects": {"auth": -1}},
    {"id": 26, "question": "The smaller the government, the freer the people.", "effects": {"auth": -1}},
    {"id": 27, "question": "The government should, at most, provide emergency services and law enforcement.", "effects": {"auth": -1}},
    {"id": 28, "question": "The police were not created to protect the people, but to uphold the status quo by force.", "effects": {"auth": -1}},
    {"id": 29, "question": "State schools are a bad idea because our state shouldn't be influencing our children.", "effects": {"auth": -1}},
    {"id": 30, "question": "Two consenting individuals should be able to do whatever they want with each other, even if it makes me uncomfortable.", "effects": {"prog": 1}},
    {"id": 31, "question": "An individual's body is their own property, and they should be able to do anything they desire to it.", "effects": {"prog": 1}},
    {"id": 32, "question": "A person should be able to worship whomever or whatever they want.", "effects": {"prog": 1}},
    {"id": 33, "question": "Nudism is perfectly natural.", "effects": {"prog": 1}},
    {"id": 34, "question": "Animals deserve certain universal rights.", "effects": {"prog": 1}},
    {"id": 35, "question": "Gender is a social construct, not a natural state of affairs.", "effects": {"prog": 1}},
    {"id": 36, "question": "Laws based on cultural values, rather than ethical ones, aren't justice.", "effects": {"prog": 1}},
    {"id": 37, "question": "Autonomy of body extends even to minors, the mentally ill, and serious criminals.", "effects": {"prog": 1}},
    {"id": 38, "question": "Homosexuality is against my values.", "effects": {"prog": -1}},
    {"id": 39, "question": "Transgender individuals should not be able to adopt children.", "effects": {"prog": -1}},
    {"id": 40, "question": "Drugs are harmful and should be banned.", "effects": {"prog": -1}},
    {"id": 41, "question": "The death penalty should exist for certain crimes.", "effects": {"prog": -1}},
    {"id": 42, "question": "Victimless crimes should still be punished.", "effects": {"prog": -1}},
    {"id": 43, "question": "One cannot be moral without religion.", "effects": {"prog": -1}},
    {"id": 44, "question": "Parents should hold absolute power over their children, as they are older and more experienced.", "effects": {"prog": -1}},
    {"id": 45, "question": "Multiculturalism is bad.", "effects": {"prog": -1}}
];
